### ISSUE TITLE
Kyte stops at conneting

### ISSUE THREAD

**Issue by agmap** [WietseWind/Zerp-Wallet#27]
Kyte stops at conneting

**Comment by WietseWind** [comment]
Hi @agmap,

Very sorry, I'm pretty certain that this was caused because the node I operate (where Kyte is connecting to) was down a few hours (while I was asleep, so I didn't notice until I woke up and I saw the monitoring messages).

Fixed that 👍

**Comment by agmap** [comment]
Same issue again
