### ISSUE TITLE
[Requirement] Air gapped TX generator

### ISSUE THREAD

**Issue by WietseWind** [WietseWind/Zerp-Wallet#3]
Create a transaction and sign using the private key. Do not send to `rippled`, but show the TX HEX (text / QR) + share (SMS/Mail/Whatsapp) so the user can send the TX air gapped.

**Comment by mDuo13** [comment]
I strongly recommend that the QR code for a signed transaction to encode a URI in the following format:

```
ripple:signed-transaction:<tx blob here>
```

(I have an unpublished document with a whole range of URI standards that may be useful for airgapped wallets, payment requests, etc.)
